apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
data:
  fluent.conf: |-
    {{ .Values.fluentdConf | nindent 4 }}
  entrypoint.sh: |-
    #!/bin/sh
  {{- range $plugin := .Values.plugins }}
    fluent-gem install {{ $plugin }}
  {{- end }}
    exec /fluentd/entrypoint.sh
