{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fluentd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: http-monitoring
  selector:
    matchLabels:
      {{- include "fluentd.selectorLabels" . | nindent 6 }}
{{- end }}
