{{- if eq .Values.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fluentd.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fluentd.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "fluentd.fullname" . }}
  template:
    {{- include "fluentd.pod" . | nindent 4 }}
{{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
