apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "haproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
data:
  haproxy.cfg: |-
    {{ .Values.haproxyConf | nindent 4 }}
